# Generated by Django 5.2.3 on 2025-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commandlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField()),
                ('command', models.TextField()),
                ('output', models.TextField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
