# Generated by Django 5.2.3 on 2025-06-30 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 30, 18, 25, 9, 431309, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
